import type { Metadata } from "next";
import { Lato, Open_Sans } from 'next/font/google';
import "./globals.css";

const lato = Lato({
  variable: "--font-lato",
  weight: ["400", "700", "900", "100", "300"],
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
