import './globals.css';
import type { Metadata } from 'next';
import { Lato, Open_Sans } from 'next/font/google';

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lato',
});

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full min-h-screen">
      <body className={`${lato.variable} ${openSans.variable} font-sans min-h-screen h-full`}>{children}</body>
    </html>
  );
}